### ISSUE TITLE
Name is dropped for POIs

### ISSUE THREAD

**Issue by hbruch** [stadtulm/photon-pelias-adapter#1]
We got complaints, that the names of bars, schools or other POIs are not displayed, but only their addresses (e.g. when searching for [Mönchberg Grundschule](https://api.mobil-in-herrenberg.de/geocoding/v1/search?text=M%C3%B6nchberg%20Grundschule&boundary.rect.min_lat=48.4521&boundary.rect.max_lat=48.85&boundary.rect.min_lon=8.5&boundary.rect.max_lon=9.278&lang=de&sources=oa%2Cosm)).

Not sure, why name is only set to the original name, [if street or house number are unset](https://github.com/stadtulm/photon-pelias-adapter/blob/master/index.js#L114)?

Comparing with results return by pelias for POIs (e.g. searching for [Airport](https://api.digitransit.fi/geocoding/v1/search?text=Airport&boundary.polygon=25.5345%2060.2592%2C25.3881%2059.9371%2C24.2831%2060.00895%2C24.3087%2060.01947%2C24.1994%2060.12753%2C24.1362%2060.1114%2C24.1305%2060.12847%2C24.099%2060.1901%2C24.0445%2060.1918%2C24.0373%2060.2036%2C24.0796%2060.2298%2C24.1652%2060.2428%2C24.3095%2060.2965%2C24.3455%2060.2488%2C24.428%2060.3002%2C24.5015%2060.2872%2C24.4888%2060.3306%2C24.5625%2060.3142%2C24.5957%2060.3242%2C24.6264%2060.3597%2C24.666%2060.3638%2C24.7436%2060.3441%2C24.9291%2060.4523%2C24.974%2060.5253%2C24.9355%2060.5131%2C24.8971%2060.562%2C25.0388%2060.5806%2C25.1508%2060.5167%2C25.1312%2060.4938%2C25.0385%2060.512%2C25.057%2060.4897%2C25.0612%2060.4485%2C25.1221%2060.4474%2C25.1188%2060.4583%2C25.149%2060.4621%2C25.1693%2060.5062%2C25.2242%2060.5016%2C25.3661%2060.4118%2C25.3652%2060.3756&lang=en&sources=oa%2Cosm%2Cnlsfi)) returns a `label` property, which contains the address components as concatenated string, e.g. `Airport Hotel Bonus Inn, Elannontie 9, Vantaa`.

Shouldn't the adapter return such a `label` property?

**Comment by leonardehrenfried** [comment]
I investigated this today and the key piece missing was the `layer` key: https://github.com/mfdz/digitransit-ui/blob/master/app/util/suggestionUtils.js#L54

If you add this, then everything looks a lot nicer.

I will test it a little more and open a pull request soon.

**Comment by leonardehrenfried** [comment]
In the meantime you can take a peek here: https://github.com/mfdz/photon-pelias-adapter

It's also deployed at https://mih.mitfahren-bw.de/
